name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    # Per Architecture Static Builds
    - name: Build Windows
      run: env GOOS=windows GOARCH=amd64 go build -a -o nvidia-clerk-windows.exe
    
    - name: Build Linux
      run: go build -a -o nvidia-clerk-linux

    - name: Build Darwin
      run: env GOOS=darwin GOARCH=amd64 go build -a -o nvidia-clerk-darwin

    - name: Test 
      run: go test -v ./...